Kriging Library: funcmod Module Reference
funcmod Module Reference
Data Types
interface func
Public Member Functions
subroutine func_toy (n, X, f, arg)
subroutine func_likelihood (n, X, f, arg)
subroutine func_likelihood_grad (n, X, f, arg)
subroutine func_likelihood_all (n, X, f, arg)
subroutine func_likelihood_all_grad (n, X, f, arg)
subroutine func_kriging (n, X, f, arg)
subroutine func_kriging_grad (n, X, f, arg)
Detailed Description
Definition at line 13 of file funcmod.f90.
Member Function/Subroutine Documentation
subroutine funcmod::func_kriging (integer, intent(in) n, real(8), dimension(n), intent(in) X, real(8), intent(out) f, type (arg_kriging), intent(in) arg)
Definition at line 84 of file funcmod.f90.
References krigingfuncpredict(), and krigingfuncvariance().
subroutine funcmod::func_kriging_grad (integer, intent(in) n, real(8), dimension(n), intent(in) X, real(8), intent(out) f, type (arg_kriging_grad), intent(in) arg)
Definition at line 123 of file funcmod.f90.
References krigingfuncpredictGEK(), and krigingfuncvarianceGEK().
subroutine funcmod::func_likelihood (integer, intent(in) n, real(8), dimension(n), intent(in) X, real(8), intent(out) f, type (arg_likelihood), intent(in) arg)
Definition at line 36 of file funcmod.f90.
subroutine funcmod::func_likelihood_all (integer, intent(in) n, real(8), dimension(n), intent(in) X, real(8), intent(out) f, type (arg_alllikelihood), intent(in) arg)
Definition at line 60 of file funcmod.f90.
subroutine funcmod::func_likelihood_all_grad (integer, intent(in) n, real(8), dimension(n), intent(in) X, real(8), intent(out) f, type (arg_alllikelihood_grad), intent(in) arg)
Definition at line 72 of file funcmod.f90.
subroutine funcmod::func_likelihood_grad (integer, intent(in) n, real(8), dimension(n), intent(in) X, real(8), intent(out) f, type (arg_likelihood_grad), intent(in) arg)
Definition at line 48 of file funcmod.f90.
subroutine funcmod::func_toy (integer, intent(in) n, real(8), dimension(n), intent(in) X, real(8), intent(out) f, type (arg_toy), intent(in) arg)
Definition at line 21 of file funcmod.f90.
References toyfunc().
The documentation for this module was generated from the following file:
funcmod.f90