Kriging Library: hyperparameters_mle_mod Module Reference
hyperparameters_mle_mod Module Reference
Data Types
interface hyperparameters_mle
Public Member Functions
subroutine hyperparameters_mle_func (ndim, ntot, X, Y, stot, H, theta, sigma, sigmaN, logpy)
Subroutine used to set up the optimization required to determine hyperparameters for a function-only Kriging model. Optimization is performed only for the length scales used in the covariance function and covariance magnitude is determined explicitly. Optimization bounds for the length scales are found here. The hard-coded noise level used to keep the covariance matrix positive-definite is also specified here.
subroutine hyperparameters_mle_grad (ndim, ntot, X, Y, gtot, pts, dims, dY, stot, H, theta, sigma, sigmaN, sigmaNG, logpy)
Subroutine used to set up the optimization required to determine hyperparameters for a gradient-enhanced Kriging model. Optimization is performed only for the length scales used in the covariance function and covariance magnitude is determined explicitly. Optimization bounds for the length scales are found here. The hard-coded noise level for the function and gradient used to keep the covariance matrix positive-definite are also specified here.
Detailed Description
Definition at line 13 of file hyperparameters_mle.f90.
Member Function/Subroutine Documentation
subroutine hyperparameters_mle_mod::hyperparameters_mle_func (integer, intent(in) ndim, integer, intent(in) ntot, real(8), dimension(ndim,ntot), intent(in) X, real(8), dimension(ntot), intent(in) Y, integer, intent(in) stot, real(8), dimension(stot,ntot), intent(in) H, real(8), dimension(ndim), intent(out) theta, real(8), intent(out) sigma, real(8), intent(out) sigmaN, real(8), intent(out) logpy)
Subroutine used to set up the optimization required to determine hyperparameters for a function-only Kriging model. Optimization is performed only for the length scales used in the covariance function and covariance magnitude is determined explicitly. Optimization bounds for the length scales are found here. The hard-coded noise level used to keep the covariance matrix positive-definite is also specified here.
Definition at line 19 of file hyperparameters_mle.f90.
References patternsearch(), and simplexsearch().
subroutine hyperparameters_mle_mod::hyperparameters_mle_grad (integer, intent(in) ndim, integer, intent(in) ntot, real(8), dimension(ndim,ntot), intent(in) X, real(8), dimension(ntot), intent(in) Y, integer, intent(in) gtot, integer, dimension(gtot), intent(in) pts, integer, dimension(gtot), intent(in) dims, real(8), dimension(gtot), intent(in) dY, integer, intent(in) stot, real(8), dimension(stot,ntot+gtot), intent(in) H, real(8), dimension(ndim), intent(out) theta, real(8), intent(out) sigma, real(8), intent(out) sigmaN, real(8), intent(out) sigmaNG, real(8), intent(out) logpy)
Subroutine used to set up the optimization required to determine hyperparameters for a gradient-enhanced Kriging model. Optimization is performed only for the length scales used in the covariance function and covariance magnitude is determined explicitly. Optimization bounds for the length scales are found here. The hard-coded noise level for the function and gradient used to keep the covariance matrix positive-definite are also specified here.
Definition at line 74 of file hyperparameters_mle.f90.
References patternsearch(), and simplexsearch().
The documentation for this module was generated from the following file:
hyperparameters_mle.f90