ForK Library: krigingfunccovar.f90 File Reference
krigingfunccovar.f90 File Reference
This subroutine calculates the covariance matrix associated with the Kriging model's output distribution. This matrix is useful when the quantifying the uncertainty of general code predictions (such as a quantile prediction or statistic prediction). This subroutine is order \(M^{2}\) in complexity, where \(M\) is the number of test points. It is very slow, so use with caution.
Functions/Subroutines
subroutine krigingfunccovar (ndim, ntot, X, stot, H, hyper, mtot, Xm, Hm, S, covarflagi)
The covariance matrix for the Kriging output distribution can be useful when predicting the uncertainty (or confidence) in general predictions based on the Kriging surface. Although the variance can be used for quantifiying the uncertainty associated with point predictions, the uncertainty associated with global predictions such as moment statistics or quantiles requires sampling from the Kriging output distribution and computing multiple estimates of this global prediction. A distribution can then be constructed for these predictions, allowing a confidence interval to be associated with the predictions from the Kriging model.
Detailed Description
This subroutine calculates the covariance matrix associated with the Kriging model's output distribution. This matrix is useful when the quantifying the uncertainty of general code predictions (such as a quantile prediction or statistic prediction). This subroutine is order \(M^{2}\) in complexity, where \(M\) is the number of test points. It is very slow, so use with caution.
Definition in file krigingfunccovar.f90.
Function Documentation
subroutine krigingfunccovar (integer,intent(in) ndim, integer,intent(in) ntot, real(8),dimension(ndim,ntot),intent(in) X, integer,intent(in) stot, real(8),dimension(stot,ntot),intent(in) H, real(8),dimension(ndim+2),intent(in) hyper, integer,intent(in) mtot, real(8),dimension(ndim,mtot),intent(in) Xm, real(8),dimension(stot,mtot),intent(in) Hm, real(8),dimension(mtot,mtot),intent(out) S, integer,intent(in) covarflagi)
The covariance matrix for the Kriging output distribution can be useful when predicting the uncertainty (or confidence) in general predictions based on the Kriging surface. Although the variance can be used for quantifiying the uncertainty associated with point predictions, the uncertainty associated with global predictions such as moment statistics or quantiles requires sampling from the Kriging output distribution and computing multiple estimates of this global prediction. A distribution can then be constructed for these predictions, allowing a confidence interval to be associated with the predictions from the Kriging model.
To sample from the Kriging model's output distribution, the output covariance matrix is constructed (S in this code) and Cholesky is performed (the result of which is denoted as \(L\)). Samples from the output distribution are given as:
\[ Y_{p} = Y_{m} + L u\]
where \(Y_{m}\) is the mean of the Kriging function's output (the result of krigingfuncpredict) and \(u\) is a vector of normally distributioned values of length \(M\) (normal distribution with zero mean and standard deviation of 1). The sampling itself is performed in the subroutine krigingfuncsample but it requires the covariance matrix to be constructed and cholesky performed.
Author:
Brian Lockwood
Department of Mechanical Engineering
University of Wyoming
Date:
May 18, 2012
Parameters:
in) ndim : The dimension of the problem
in) ntot : The number of Training points
in) X : The location of the training points (size=[ndimxntot])
in) stot : Number of Terms in the regression
in) H: The collocation matrix for the regression (size=[stotxntot])
in) hyper: Hyperparameters for the Kriging Model (size=[ndim+2])
Supplied by buildkriging subroutine
in) mtot : The number of test points, the places where function prediction are desired
in) Xm : The location of the test points (size=[ndimxmtot])
in) Hm : The collocation matrix evaluated at the test points (size=[stotxmtot])
out) S: Covariance matrix between function values (size=[mtotxmtot])
in) covarflagi: Flag to govern which covariance function is used
covarflag==0 Uses Matern function with \(\nu=1/2\)
covarflag==1 Uses Matern function with \(\nu=3/2\)
covarflag==2 Uses Matern function with \(\nu=5/2\)
The parameter \(\nu\) governs the smoothness and differentiability of the covariance function. For function only Kriging, all three options are available.
Must supply the same covariance flag as used in buildkriging.
Definition at line 40 of file krigingfunccovar.f90.
References covars::covarflag, covars::covarfunc(), choleskymod::invertsymmetric(), choleskymod::matrixmulttrans(), choleskymod::symmatrixmult(), and choleskymod::symmatrixmulttrans().