ForK Library: choleskymod Module Reference
choleskymod Module Reference
Functions/Subroutines
subroutine cholesky (n, A)
Subroutine to perform Cholesky factorization in place and stored as a lower triangular (uses LAPACK).
subroutine choleskysolve (n, A, b, x)
Subroutine to solve Ax=b if A is a cholesky factorized matrix stored as a lower triangular.
subroutine invertcholesky (n, A, Ai)
Subroutine to invert a cholesky factorized matrix.
subroutine invertsymmetric (n, A)
Subroutine to invert a positive definite symmetric matrix and store the inverse in place (uses LAPACK). Result stored as a lower triangular matrix.
subroutine symmetricsolve (n, A, x)
Solves Ax=b for a symmetric positive definite matrix. Initial value of X is the vector b and the final value is the solution. Uses LAPACK.
subroutine matrixmult (n, m, A, p, B, C)
Subroutine that performs matrix multiplication \(A*B=C\). Uses LAPACK.
subroutine symmatrixmult (n, A, p, B, C)
Subroutine that performs matrix multiplication \(A*B=C\) when A is symmetric. Uses LAPACK.
subroutine matrixmulttrans (n, m, A, p, B, C)
Subroutine that performs matrix multiplication as \(A*B^{T}=C\). Uses LAPACK.
subroutine symmatrixmulttrans (n, A, p, B, C)
Subroutine that performs matrix multiplication as \(A*B^{T}=C\) when A is symmetric. Uses LAPACK.
subroutine matvec (n, m, A, x, B)
Subroutine that performs matrix-vector multiplication as \(A x = b \). Uses LAPACK.
subroutine symmatvec (n, A, x, B)
Subroutine that performs matrix-vector multiplication as \(A x = b \) when A is symmetric. Uses LAPACK.
subroutine matvectrans (n, m, A, x, B)
Subroutine that performs matrix-vector multiplication as \(A^{T} x = b \). Uses LAPACK.
Function/Subroutine Documentation
subroutine choleskymod::cholesky (integer,intent(in) n, real(8),dimension(n,n),intent(inout) A)
Subroutine to perform Cholesky factorization in place and stored as a lower triangular (uses LAPACK).
Definition at line 30 of file choleskymod.f90.
Referenced by invertsymmetric(), magnitude_mod::magnitude_func(), magnitude_mod::magnitude_grad(), and symmetricsolve().
subroutine choleskymod::choleskysolve (integer,intent(in) n, real(8),dimension(n,n),intent(in) A, real(8),dimension(n),intent(in) b, real(8),dimension(n),intent(out) x)
Subroutine to solve Ax=b if A is a cholesky factorized matrix stored as a lower triangular.
Definition at line 66 of file choleskymod.f90.
Referenced by invertcholesky(), magnitude_mod::magnitude_func(), magnitude_mod::magnitude_grad(), and symmetricsolve().
subroutine choleskymod::invertcholesky (integer,intent(in) n, real(8),dimension(n,n),intent(in) A, real(8),dimension(n,n),intent(out) Ai)
Subroutine to invert a cholesky factorized matrix.
Definition at line 93 of file choleskymod.f90.
References choleskysolve().
Referenced by invertsymmetric(), magnitude_mod::magnitude_func(), and magnitude_mod::magnitude_grad().
subroutine choleskymod::invertsymmetric (integer,intent(in) n, real(8),dimension(n,n),intent(inout) A)
Subroutine to invert a positive definite symmetric matrix and store the inverse in place (uses LAPACK). Result stored as a lower triangular matrix.
Definition at line 135 of file choleskymod.f90.
References cholesky(), and invertcholesky().
Referenced by buildkriging(), buildkrigingGEK(), krigingfunccovar(), krigingfuncvariance(), krigingfuncvarianceGEK(), kriginggradvariance(), kriginggradvarianceGEK(), likelihood_mod::likelihood_func(), likelihood_mod::likelihood_grad(), likelihood_mle_mod::likelihood_mle_func(), and likelihood_mle_mod::likelihood_mle_grad().
subroutine choleskymod::matrixmult (integer,intent(in) n, integer,intent(in) m, real(8),dimension(n,m),intent(in) A, integer,intent(in) p, real(8),dimension(m,p),intent(in) B, real(8),dimension(n,p),intent(out) C)
Subroutine that performs matrix multiplication \(A*B=C\). Uses LAPACK.
Definition at line 197 of file choleskymod.f90.
subroutine choleskymod::matrixmulttrans (integer,intent(in) n, integer,intent(in) m, real(8),dimension(n,m),intent(in) A, integer,intent(in) p, real(8),dimension(p,m),intent(in) B, real(8),dimension(p,n),intent(out) C)
Subroutine that performs matrix multiplication as \(A*B^{T}=C\). Uses LAPACK.
Definition at line 272 of file choleskymod.f90.
Referenced by buildkriging(), buildkrigingGEK(), krigingfunccovar(), krigingfuncvariance(), krigingfuncvarianceGEK(), kriginggradvariance(), kriginggradvarianceGEK(), likelihood_mod::likelihood_func(), likelihood_mod::likelihood_grad(), likelihood_mle_mod::likelihood_mle_func(), and likelihood_mle_mod::likelihood_mle_grad().
subroutine choleskymod::matvec (integer,intent(in) n, integer,intent(in) m, real(8),dimension(n,m),intent(in) A, real(8),dimension(m),intent(in) x, real(8),dimension(n),intent(out) B)
Subroutine that performs matrix-vector multiplication as \(A x = b \). Uses LAPACK.
Definition at line 346 of file choleskymod.f90.
Referenced by buildkriging(), buildkrigingGEK(), likelihood_mod::likelihood_func(), likelihood_mod::likelihood_grad(), likelihood_mle_mod::likelihood_mle_func(), and likelihood_mle_mod::likelihood_mle_grad().
subroutine choleskymod::matvectrans (integer,intent(in) n, integer,intent(in) m, real(8),dimension(n,m),intent(in) A, real(8),dimension(n),intent(in) x, real(8),dimension(m),intent(out) B)
Subroutine that performs matrix-vector multiplication as \(A^{T} x = b \). Uses LAPACK.
Definition at line 416 of file choleskymod.f90.
Referenced by buildkriging(), buildkrigingGEK(), likelihood_mod::likelihood_func(), likelihood_mod::likelihood_grad(), likelihood_mle_mod::likelihood_mle_func(), and likelihood_mle_mod::likelihood_mle_grad().
subroutine choleskymod::symmatrixmult (integer,intent(in) n, real(8),dimension(n,n),intent(in) A, integer,intent(in) p, real(8),dimension(n,p),intent(in) B, real(8),dimension(n,p),intent(out) C)
Subroutine that performs matrix multiplication \(A*B=C\) when A is symmetric. Uses LAPACK.
Definition at line 234 of file choleskymod.f90.
Referenced by krigingfunccovar().
subroutine choleskymod::symmatrixmulttrans (integer,intent(in) n, real(8),dimension(n,n),intent(in) A, integer,intent(in) p, real(8),dimension(p,n),intent(in) B, real(8),dimension(p,n),intent(out) C)
Subroutine that performs matrix multiplication as \(A*B^{T}=C\) when A is symmetric. Uses LAPACK.
Definition at line 309 of file choleskymod.f90.
Referenced by buildkriging(), buildkrigingGEK(), krigingfunccovar(), krigingfuncvariance(), krigingfuncvarianceGEK(), kriginggradvariance(), kriginggradvarianceGEK(), likelihood_mod::likelihood_func(), likelihood_mod::likelihood_grad(), likelihood_mle_mod::likelihood_mle_func(), and likelihood_mle_mod::likelihood_mle_grad().
subroutine choleskymod::symmatvec (integer,intent(in) n, real(8),dimension(n,n),intent(in) A, real(8),dimension(n),intent(in) x, real(8),dimension(n),intent(out) B)
Subroutine that performs matrix-vector multiplication as \(A x = b \) when A is symmetric. Uses LAPACK.
Definition at line 381 of file choleskymod.f90.
Referenced by buildkriging(), buildkrigingGEK(), krigingfuncvariance(), krigingfuncvarianceGEK(), kriginggradvariance(), kriginggradvarianceGEK(), likelihood_mod::likelihood_func(), likelihood_mod::likelihood_grad(), likelihood_mle_mod::likelihood_mle_func(), and likelihood_mle_mod::likelihood_mle_grad().
subroutine choleskymod::symmetricsolve (integer,intent(in) n, real(8),dimension(n,n),intent(inout) A, real(8),dimension(n),intent(inout) X)
Solves Ax=b for a symmetric positive definite matrix. Initial value of X is the vector b and the final value is the solution. Uses LAPACK.
Definition at line 167 of file choleskymod.f90.
References cholesky(), and choleskysolve().
Referenced by buildkriging(), buildkrigingGEK(), likelihood_mod::likelihood_func(), likelihood_mod::likelihood_grad(), likelihood_mle_mod::likelihood_mle_func(), and likelihood_mle_mod::likelihood_mle_grad().