ForK Library: hyperparameters_all_mod Module Reference
hyperparameters_all_mod Module Reference
Data Types
interface hyperparameters_all
Functions/Subroutines
subroutine hyperparameters_all_func (ndim, ntot, X, Y, stot, H, theta, sigma, sigmaN, logpy)
Subroutine used to set up the optimization required to determine the best hyperparameters for a function-only Kriging model using the Vague Prior mean function. Optimization is used to determine all hyperparameters, including the covariance magnitude and noise. Optimization bounds for each parameter are located here.
subroutine hyperparameters_all_grad (ndim, ntot, X, Y, gtot, pts, dims, dY, stot, H, theta, sigma, sigmaN, sigmaNG, logpy)
Subroutine used to set up the optimization required to determine the best hyperparameters for a gradient-enhanced Kriging model using the Vague Prior mean function. Optimization is used to determine all hyperparameters, including the covariance magnitude, function noise level and derivative noise level. Optimization bounds for each parameter are located here.
Function/Subroutine Documentation
subroutine hyperparameters_all_mod::hyperparameters_all_func (integer,intent(in) ndim, integer,intent(in) ntot, real(8),dimension(ndim,ntot),intent(in) X, real(8),dimension(ntot),intent(in) Y, integer,intent(in) stot, real(8),dimension(stot,ntot),intent(in) H, real(8),dimension(ndim),intent(out) theta, real(8),intent(out) sigma, real(8),intent(out) sigmaN, real(8),intent(out) logpy)
Subroutine used to set up the optimization required to determine the best hyperparameters for a function-only Kriging model using the Vague Prior mean function. Optimization is used to determine all hyperparameters, including the covariance magnitude and noise. Optimization bounds for each parameter are located here.
Definition at line 19 of file hyperparameters_all.f90.
References opt::optflag, patternsearch(), and simplexsearch().
subroutine hyperparameters_all_mod::hyperparameters_all_grad (integer,intent(in) ndim, integer,intent(in) ntot, real(8),dimension(ndim,ntot),intent(in) X, real(8),dimension(ntot),intent(in) Y, integer,intent(in) gtot, integer,dimension(gtot),intent(in) pts, integer,dimension(gtot),intent(in) dims, real(8),dimension(gtot),intent(in) dY, integer,intent(in) stot, real(8),dimension(stot,ntot+gtot),intent(in) H, real(8),dimension(ndim),intent(out) theta, real(8),intent(out) sigma, real(8),intent(out) sigmaN, real(8),intent(out) sigmaNG, real(8),intent(out) logpy)
Subroutine used to set up the optimization required to determine the best hyperparameters for a gradient-enhanced Kriging model using the Vague Prior mean function. Optimization is used to determine all hyperparameters, including the covariance magnitude, function noise level and derivative noise level. Optimization bounds for each parameter are located here.
Definition at line 86 of file hyperparameters_all.f90.
References opt::optflag, patternsearch(), and simplexsearch().