ForK Library: opt Module Reference
opt Module Reference
Functions/Subroutines
subroutine forcingfunc (t, rho)
subroutine expansionfunc (t, theta)
subroutine contractionfunc (t, theta)
Variables
integer optflag
Function/Subroutine Documentation
subroutine opt::contractionfunc (real(8),intent(in) t, real(8),intent(out) theta)
Definition at line 38 of file opt.f90.
Referenced by patternsearch().
subroutine opt::expansionfunc (real(8),intent(in) t, real(8),intent(out) theta)
Definition at line 28 of file opt.f90.
Referenced by patternsearch().
subroutine opt::forcingfunc (real(8),intent(in) t, real(8),intent(out) rho)
Definition at line 17 of file opt.f90.
Referenced by patternsearch().
Variable Documentation
integer opt::optflag
Definition at line 15 of file opt.f90.
Referenced by buildkriging(), buildkrigingGEK(), hyperparameters_all_mod::hyperparameters_all_func(), hyperparameters_all_mod::hyperparameters_all_grad(), hyperparameters_mle_mod::hyperparameters_mle_func(), and hyperparameters_mle_mod::hyperparameters_mle_grad().