ForK Library: covars Module Reference
covars Module Reference
Functions/Subroutines
real(8) covar1d (X, Xt, theta)
Function used to calculate the one dimensional covariance functions used to construct the multidimensional functions.
real(8) dcovar1d (X, Xt, theta)
Function used to calculate the derivative of the one dimensional covariance functions with respect to the first coordinate.
real(8) d2covar1d (X, Xt, theta)
Function used to calculate the second derivative of the one dimensional covariance functions with respect to the second coordinate.
subroutine covarfunc (ndim, X, Xt, theta, k)
Subroutine for computing the multidimensional covariance between two data points.
subroutine dcovarfunc (ndim, X, Xt, theta, dk)
Subroutine for computing the gradient of the multidimensional covariance function.
subroutine d2covarfunc (ndim, X, Xt, theta, d2k)
Subroutine for computing the Hessian of the multidimensional covariance function. The second derivative is performed with respect to the second coordinate.
Variables
integer covarflag
real(8), parameter root3 = sqrt(3.d0)
real(8), parameter root5 = sqrt(5.d0)
real(8), parameter third = 1.D0/3.D0
Function/Subroutine Documentation
real(8) covars::covar1d (real(8),intent(in) X, real(8),intent(in) Xt, real(8),intent(in) theta)
Function used to calculate the one dimensional covariance functions used to construct the multidimensional functions.
This function calculates the one dimensional Matern function with three possible values the parameter \(\nu \) (specified with the variable covarflag). The three possible functions are given as:
\[ k(x,x') = \begin{cases} e^{-r} & \text{for $\nu = 1/2$,} \\ \left(1 + \sqrt{3} r \right) e^{-\sqrt{3} r} & \text{for $\nu = 3/2$,} \\ \left(1 + \sqrt{5} r+ \frac{5}{3} r^{2} \right) e^{-\sqrt{5} r} & \text{for $\nu = 5/2$,} \end{cases}\]
where \(r\) is defined as:
\[ r = \bigg \vert \frac{X - X'}{\theta} \bigg \vert \]
Author:
Brian Lockwood
Department of Mechanical Engineering
University of Wyoming
Date:
May 17, 2012
Parameters:
in) X : Coordinate of the first point
in) Xt: Coordinate of the second point
in) theta: Length scale in the dimension
in) covarflag: Flag to govern which covariance function is used (stored as global variable in this module)
covarflag==0 Uses Matern function with \(\nu=1/2\)
covarflag==1 Uses Matern function with \(\nu=3/2\)
covarflag==2 Uses Matern function with \(\nu=5/2\)
Return values:
covar1d the 1-D Covariance value
Definition at line 40 of file covars.f90.
References covarflag, root3, root5, and third.
Referenced by covarfunc(), d2covarfunc(), and dcovarfunc().
subroutine covars::covarfunc (integer,intent(in) ndim, real(8),dimension(ndim),intent(in) X, real(8),dimension(ndim),intent(in) Xt, real(8),dimension(ndim),intent(in) theta, real(8),intent(out) k)
Subroutine for computing the multidimensional covariance between two data points.
Multidimensional covariance is built up using a tensor product of 1 dimensional covariance functions:
\[ k(\vec{X},\vec{X}'; \theta) = \prod_{i}^{d} k_{i}\left(\bigg \vert \frac{X_{i} - X'_{i}}{\theta_{i}} \bigg \vert\right)\]
where \(D\) is the dimension of the problem. The 1-D covariance functions are defined in function covar1d
Author:
Brian Lockwood Department of Mechanical Engineering University of Wyoming
Date:
May 3, 2012
Parameters:
in) ndim : The dimension of the problem
in) X : Coordinates of the first point (size=[ndim])
in) Xt : Coordinates of the second point (size=[ndim])
in) theta : Length scale in each dimension
out) k : Covariance value
Definition at line 164 of file covars.f90.
References covar1d().
Referenced by covarmatrix_mod::covarmatrix_gen(), covarmatrix_mod::covarmatrix_gen_grad(), covarmatrix_mod::covarmatrix_training(), covarmatrix_mod::covarmatrix_training_grad(), krigingfunccovar(), krigingfuncvariance(), and krigingfuncvarianceGEK().
real(8) covars::d2covar1d (real(8),intent(in) X, real(8),intent(in) Xt, real(8),intent(in) theta)
Function used to calculate the second derivative of the one dimensional covariance functions with respect to the second coordinate.
This function calculates the second derivative of the one dimensional Matern function with three possible values the parameter \(\nu \) (specified with the variable covarflag). The second derivative of interest is the derivative of the result of dcovar1d with respect to the argument Xt. This derivative is required for the covariance between derivative values:
\[ cov(\frac{d y}{d x}, \frac{d y'}{d x}) = \frac{d^{2}}{dx dx'} k(X,X',\theta) \]
The practical result of differeniating with repsect to the second argument is that an extra negative sign appears. Hence, the second derivative of the Matern functions with respect to \(r\) can be calculated and an additional negative sign can be applied to the result to yield the required derivative value.
Author:
Brian Lockwood
Department of Mechanical Engineering
University of Wyoming
Date:
May 17, 2012
Parameters:
in) X : Coordinate of the first point
in) Xt: Coordinate of the second point
in) : Length scale in the dimension
in) covarflag: Flag to govern which covariance function is used (stored as global variable in this module)
covarflag==0 Uses Matern function with \(\nu=1/2\)
covarflag==1 Uses Matern function with \(\nu=3/2\)
covarflag==2 Uses Matern function with \(\nu=5/2\)
Return values:
d2covar1d The second derivative of the Covariance w.r.t. Xt
Definition at line 120 of file covars.f90.
References covarflag, root3, root5, and third.
Referenced by d2covarfunc().
subroutine covars::d2covarfunc (integer,intent(in) ndim, real(8),dimension(ndim),intent(in) X, real(8),dimension(ndim),intent(in) Xt, real(8),dimension(ndim),intent(in) theta, real(8),dimension(ndim,ndim),intent(out) d2k)
Subroutine for computing the Hessian of the multidimensional covariance function. The second derivative is performed with respect to the second coordinate.
The multidimensional covariance is built up using a tensor product of 1 dimensional covariance functions:
\[ k(\vec{X},\vec{X}'; \theta) = \prod_{i}^{D} k_{i} \left(\bigg \vert \frac{X_{i} - X'_{i}}{\theta_{i}} \bigg \vert \right) \]
where \(D\) is the dimension of the problem. The 1-D covariance functions are defined in function covar1d The derivative of this covariance with respect to the coordinate \(x_{j}\) can be written as:
\[ \frac{\partial}{\partial x_{j}} k(\vec{X},\vec{X}'; \theta) = \frac{d}{dx_{j}} k_{j} \left(\bigg \vert \frac{X_{j} - X'_{j}}{\theta_{j}} \bigg \vert \right) \prod_{i \ne j} k_{i} \left(\bigg \vert \frac{X_{i} - X'_{i}}{\theta_{i}} \bigg \vert \right)\]
The second derivative of the covariance with repect to the \(l\) component of the second coordinate \(x'_{l}\) is given as:
\[ \frac{\partial^{2}}{\partial x_{j} \partial x'_{l}} k(\vec{X},\vec{X}'; \theta) = \begin{cases} \frac{d^{2}}{dx_{j} dx'_{j}} k_{j} \left(\bigg \vert \frac{X_{j} - X'_{j}}{\theta_{j}} \bigg \vert \right) \prod_{i \ne j} k_{i} \left(\bigg \vert \frac{X_{i} - X'_{i}}{\theta_{i}} \bigg \vert \right) \text{ for $l=j$, } \\ -\frac{d}{dx_{j}} k_{j} \left(\bigg \vert \frac{X_{j} - X'_{j}}{\theta_{j}} \bigg \vert \right) \frac{d}{dx_{l}} k_{l} \left(\bigg \vert \frac{X_{l} - X'_{l}}{\theta_{l}} \bigg \vert \right) \prod_{i \ne j \ne l} k_{i} \left(\bigg \vert \frac{X_{i} - X'_{i}}{\theta_{i}} \bigg \vert \right) \text{ for $l \ne j$} \end{cases} \]
$ The entire Hessian can be computed efficiently by storing the following intermediate products as well as the 1-D covariance function values. Define the lower product as:
\[ L_{j} = \prod_{i<j} k_{i} \left(\bigg \vert \frac{X_{i} - X'_{i}}{\theta_{i}} \bigg \vert \right) \]
, the upper product as:
\[ U_{j} = \prod_{i>j} k_{i} \left(\bigg \vert \frac{X_{i} - X'_{i}}{\theta_{i}} \bigg \vert \right) \]
and the intermediate product as:
\[ M_{l,j} = \prod_{l<i<j} k_{i} \left(\bigg \vert \frac{X_{i} - X'_{i}}{\theta_{i}} \bigg \vert \right) \]
, the hessian of the covariance can be computed as:
\[ \frac{\partial^{2}}{\partial x_{j} \partial x'_{l}} k(\vec{X},\vec{X}'; \theta) = \begin{cases} L_{j} \frac{d^{2}}{dx_{j} dx'_{j}} k_{j} \left(\bigg \vert \frac{X_{j} - X'_{j}}{\theta_{j}} \bigg \vert \right) U_{j} \text{ for $l=j$, } \\ -L_{j} \frac{d}{dx_{j}} k_{j} \left(\bigg \vert \frac{X_{j} - X'_{j}}{\theta_{j}} \bigg \vert \right) M{j,l} \frac{d}{dx_{l}} k_{l} \left(\bigg \vert \frac{X_{l} - X'_{l}}{\theta_{l}} \bigg \vert \right) U_{l} \text{ for $l \ne j$} \end{cases} \]
. The lower, upper and intermediate products can be built up recursively based on the stored 1-D covariance function values. This allows the full Hessian to be calculated in order \(D^{2}\) time. For the intermediate product, the diagonal and sub-diagonal is defined as:
\[\begin{cases} M_{j,j} = 1 & \text{for $j=1,..,D$, } \\ M_{j,j+1} = 1 & \text{for $j=1,..,D-1$, } \end{cases} \]
Further cost savings are realized by utilizing the fact that the Hessian is symmetric. Hence, only the upper diagonal components of the Hessian are analytically computed and the result of this calculation is copied to the lower diagonal components.
Author:
Brian Lockwood Department of Mechanical Engineering University of Wyoming
Date:
May 3, 2012
Parameters:
in) ndim : The dimension of the problem
in) X : Coordinates of the first point (size=[ndim])
in) Xt : Coordinates of the second point (size=[ndim])
in) theta : Length scale in each dimension
out) dk : Covariance value
Definition at line 300 of file covars.f90.
References covar1d(), d2covar1d(), and dcovar1d().
Referenced by covarmatrix_mod::covarmatrix_gen_grad(), covarmatrix_grad_mod::covarmatrix_grad_gek(), covarmatrix_mod::covarmatrix_training_grad(), kriginggradvariance(), and kriginggradvarianceGEK().
real(8) covars::dcovar1d (real(8),intent(in) X, real(8),intent(in) Xt, real(8),intent(in) theta)
Function used to calculate the derivative of the one dimensional covariance functions with respect to the first coordinate.
This function calculates the derivative of the one dimensional Matern function with three possible values the parameter \(\nu \) (specified with the variable covarflag). The derivative is performed with respect to the first coordinate (X). This derivative is required for the covariance between function and derivative values:
\[ cov(y, \frac{d y}{d x}) = \frac{d}{dx} k(X,X',\theta) \]
.
Author:
Brian Lockwood
Department of Mechanical Engineering
University of Wyoming
Date:
May 17, 2012
Parameters:
in) X : Coordinate of the first point
in) Xt: Coordinate of the second point
in) : Length scale in the dimension
in) covarflag: Flag to govern which covariance function is used (stored as global variable in this module)
covarflag==0 Uses Matern function with \(\nu=1/2\)
covarflag==1 Uses Matern function with \(\nu=3/2\)
covarflag==2 Uses Matern function with \(\nu=5/2\)
Return values:
dcovar1d the Derivative of the Covariance w.r.t. X
Definition at line 78 of file covars.f90.
References covarflag, root3, root5, and third.
Referenced by d2covarfunc(), and dcovarfunc().
subroutine covars::dcovarfunc (integer,intent(in) ndim, real(8),dimension(ndim),intent(in) X, real(8),dimension(ndim),intent(in) Xt, real(8),dimension(ndim),intent(in) theta, real(8),dimension(ndim),intent(out) dk)
Subroutine for computing the gradient of the multidimensional covariance function.
The multidimensional covariance is built up using a tensor product of 1 dimensional covariance functions:
\[ k(\vec{X},\vec{X}'; \theta) = \prod_{i}^{D} k_{i}\left(\bigg \vert \frac{X_{i} - X'_{i}}{\theta_{i}} \bigg \vert \right)\]
where \(D\) is the dimension of the problem. The 1-D covariance functions are defined in function covar1d The derivative of this covariance with respect to the coordinate \(x_{j}\) can be written as:
\[ \frac{\partial}{\partial x_{j}} k(\vec{X},\vec{X}'; \theta) = \frac{d}{dx_{j}} k_{j} \left(\bigg \vert \frac{X_{j} - X'_{j}}{\theta_{j}} \bigg \vert \right) \prod_{i \ne j} k_{i} \left(\bigg \vert \frac{X_{i} - X'_{i}}{\theta_{i}} \bigg \vert \right)\]
Although conceptually easy, the above formula for the derivative of the covariance function is inefficient as the complexity is order \(D^{2}\). Using memoization, the gradient can be computed in order \(D\) time by computed and storing several intermediate products. Defining the lower product as:
\[ L_{j} = \prod_{i<j} k_{i} \left(\bigg \vert \frac{X_{i} - X'_{i}}{\theta_{i}} \bigg \vert \right) \]
and the upper product as:
\[ U_{j} = \prod_{i>j} k_{i}\left(\bigg \vert \frac{X_{i} - X'_{i}}{\theta_{i}} \bigg \vert \right) \]
, the derivative can be computed as:
\[ \frac{\partial}{\partial x_{j}} = L_{j} \frac{d}{dx_{j}} k_{j} \left(\bigg \vert \frac{X_{j} - X'_{j}}{\theta_{j}} \bigg \vert \right) U_{j} \]
By storing the 1-D covariance function values, the upper and lower products can be built up recursively in order \(D\) time. The use of these upper and lower products allows for the re-use of work for each component of the gradient, reducing the cost of constructing the entire gradient.
Author:
Brian Lockwood Department of Mechanical Engineering University of Wyoming
Date:
May 3, 2012
Parameters:
in) ndim : The dimension of the problem
in) X : Coordinates of the first point (size=[ndim])
in) Xt : Coordinates of the second point (size=[ndim])
in) theta : Length scale in each dimension
out) dk : Covariance value
Definition at line 218 of file covars.f90.
References covar1d(), and dcovar1d().
Referenced by covarmatrix_mod::covarmatrix_gen_grad(), covarmatrix_grad_mod::covarmatrix_grad_func(), covarmatrix_grad_mod::covarmatrix_grad_gek(), and covarmatrix_mod::covarmatrix_training_grad().
Variable Documentation
integer covars::covarflag
Definition at line 14 of file covars.f90.
Referenced by buildkriging(), buildkrigingGEK(), covar1d(), d2covar1d(), dcovar1d(), krigingfunccovar(), krigingfuncpredict(), krigingfuncpredictGEK(), krigingfuncvariance(), krigingfuncvarianceGEK(), kriginggradpredict(), kriginggradpredictGEK(), kriginggradvariance(), and kriginggradvarianceGEK().
real(8),parameter covars::root3 = sqrt(3.d0)
Definition at line 15 of file covars.f90.
Referenced by covar1d(), d2covar1d(), and dcovar1d().
real(8),parameter covars::root5 = sqrt(5.d0)
Definition at line 16 of file covars.f90.
Referenced by covar1d(), d2covar1d(), and dcovar1d().
real(8),parameter covars::third = 1.D0/3.D0
Definition at line 17 of file covars.f90.
Referenced by covar1d(), d2covar1d(), and dcovar1d().