ForK Library: likelihood_mod Module Reference
likelihood_mod Module Reference
Data Types
interface likelihood
Functions/Subroutines
subroutine likelihood_func (ndim, ntot, X, Y, stot, H, theta, sigma, sigmaN, logpy)
Subroutine for computing the likelihood formula for a function only Kriging model where noise level and covariance magnitude can be varied independently.
subroutine likelihood_grad (ndim, ntot, X, Y, gtot, pts, dims, dY, stot, H, theta, sigma, sigmaN, sigmaNG, logpy)
Subroutine used for computing the likelihood formula for a gradient-enhanced Kriging model where funtion noise level, derivative noise level and covariance magnitude can be varied independently.
Function/Subroutine Documentation
subroutine likelihood_mod::likelihood_func (integer,intent(in) ndim, integer,intent(in) ntot, real(8),dimension(ndim,ntot),intent(in) X, real(8),dimension(ntot),intent(in) Y, integer,intent(in) stot, real(8),dimension(stot,ntot),intent(in) H, real(8),dimension(ndim),intent(in) theta, real(8),intent(in) sigma, real(8),intent(in) sigmaN, real(8),intent(out) logpy)
Subroutine for computing the likelihood formula for a function only Kriging model where noise level and covariance magnitude can be varied independently.
The likelihood formula for a Gaussian process with a regression mean function is given by:
\[ \log p(y | X; \theta) = -\frac{1}{2} Y^{T} K^{-1} (Y - H^{T} \beta) - \frac{1}{2} \log \vert K \vert - \frac{1}{2} \log \vert A \vert - \frac{N-S}{2} \log 2\pi \]
where \(N\) is the number of training points (denoted by the argument ntot) and \(S\) is the number of terms in the regression (given by the argument stot). Here a vague prior on the regression parameters, \(\beta \) has been assumed (meaning that the distribution of these parameters is not known). The optimal regression parameters are given by:
\[ \beta = A^{-1} H Y \]
where the regression matrix \(A \) is defined as:
\[ A = H K^{-1} H^{T} \]
. Both the covariance matrix and regression matrix are symmetric positive definite, allowing cholesky to be performed on both matrices. This cholesky factorization is used to invert these matrices as well as compute the determinant. For a cholesky-factorized matrix (applicable for the regression and covariance matrix), the logarithm of the determinant is given as:
\[ \log \vert C \vert = \log \vert L L^{T} \vert = 2 \sum_{k} L_{k,k} \]
The subroutine below stores the inverse of the covariance in place. In the case that the cholesky of the inverse of the matrix is available, the determinant of the original matrix is found by applying a negative sign.
\[ \log \vert C \vert = \log \vert (L^{-1} L^{-T})^{-1} \vert = - 2 \sum_{k} L^{-1}_{k,k} \]
Further details of the likelihood formula used in this subroutine can be found in Chapter 2 of Gaussian Processes for Machine Learning by Rasmussen and Williams.
Author:
Brian Lockwood Department of Mechanical Engineering University of Wyoming
Date:
May 17, 2012
Parameters:
in) ndim : The dimension of the problem
in) ntot : The number of training points
in) X : Location of the training points (size=[ndimxntot])
in) Y : Funcation values for the training points (size=[ntot])
in) stot : Number of Terms in the regression
in) H: The collocation matrix for the regression (size=[stotxntot])
in) theta : Length scale in each direction (size=[ndim])
in) sigma : Covariance Magnitude
in) sigmaN : Noise Magnitude (added to diagonal of covariance matrix)
out) logpy : Natural Logarithm of the likelihood (\(p(y | X,\theta, \sigma, \sigma_{N})\)
Definition at line 52 of file likelihood.f90.
References choleskymod::invertsymmetric(), choleskymod::matrixmulttrans(), choleskymod::matvec(), choleskymod::matvectrans(), choleskymod::symmatrixmulttrans(), choleskymod::symmatvec(), and choleskymod::symmetricsolve().
subroutine likelihood_mod::likelihood_grad (integer,intent(in) ndim, integer,intent(in) ntot, real(8),dimension(ndim,ntot),intent(in) X, real(8),dimension(ntot),intent(in) Y, integer,intent(in) gtot, integer,dimension(gtot),intent(in) pts, integer,dimension(gtot),intent(in) dims, real(8),dimension(gtot),intent(in) dY, integer,intent(in) stot, real(8),dimension(stot,ntot+gtot),intent(in) H, real(8),dimension(ndim),intent(in) theta, real(8),intent(in) sigma, real(8),intent(in) sigmaN, real(8),intent(in) sigmaNG, real(8),intent(out) logpy)
Subroutine used for computing the likelihood formula for a gradient-enhanced Kriging model where funtion noise level, derivative noise level and covariance magnitude can be varied independently.
Definition at line 127 of file likelihood.f90.
References choleskymod::invertsymmetric(), choleskymod::matrixmulttrans(), choleskymod::matvec(), choleskymod::matvectrans(), choleskymod::symmatrixmulttrans(), choleskymod::symmatvec(), and choleskymod::symmetricsolve().