ForK Library: covarmatrix_mod Module Reference
covarmatrix_mod Module Reference
Data Types
interface covarmatrix
Functions/Subroutines
subroutine covarmatrix_training (ndim, ntot, X, theta, Kmat)
Subroutine to create the covariance matrix between training points for a function-only Kriging model.
subroutine covarmatrix_training_grad (ndim, ntot, gtot, pts, dims, X, theta, Kmat)
Subroutine to create covariance matrix between training points for gradient-enhanced Kriging model. This matrix is a block matrix where the diagonals represent covariance between function values and derivative values and the off-diagonals represent the covaraince between function and derivative values.
subroutine covarmatrix_gen (ndim, ntot, X, mtot, Xm, theta, Kmat)
Builds a general covariance matrix between two sets of points for a function-only Kriging model. It is used to construct the covariance between training points and test points.
subroutine covarmatrix_gen_grad (ndim, ntot, gtot, pts, dims, X, mtot, htot, ptsm, dimsm, Xm, theta, Kmat)
Builds a general covariance matrix between two sets of points for a gradient-enhanced Kriging model. Includes the covariance between function and derivative values.
Function/Subroutine Documentation
subroutine covarmatrix_mod::covarmatrix_gen (integer,intent(in) ndim, integer,intent(in) ntot, real(8),dimension(ndim,ntot),intent(in) X, integer,intent(in) mtot, real(8),dimension(ndim,mtot),intent(in) Xm, real(8),dimension(ndim),intent(in) theta, real(8),dimension(ntot,mtot),intent(out) Kmat)
Builds a general covariance matrix between two sets of points for a function-only Kriging model. It is used to construct the covariance between training points and test points.
Definition at line 107 of file covarmatrix.f90.
References covars::covarfunc().
subroutine covarmatrix_mod::covarmatrix_gen_grad (integer,intent(in) ndim, integer,intent(in) ntot, integer,intent(in) gtot, integer,dimension(gtot),intent(in) pts, integer,dimension(gtot),intent(in) dims, real(8),dimension(ndim,ntot),intent(in) X, integer,intent(in) mtot, integer,intent(in) htot, integer,dimension(htot),intent(in) ptsm, integer,dimension(htot),intent(in) dimsm, real(8),dimension(ndim,mtot),intent(in) Xm, real(8),dimension(ndim),intent(in) theta, real(8),dimension(ntot+gtot,mtot+htot),intent(out) Kmat)
Builds a general covariance matrix between two sets of points for a gradient-enhanced Kriging model. Includes the covariance between function and derivative values.
Definition at line 134 of file covarmatrix.f90.
References covars::covarfunc(), covars::d2covarfunc(), and covars::dcovarfunc().
subroutine covarmatrix_mod::covarmatrix_training (integer,intent(in) ndim, integer,intent(in) ntot, real(8),dimension(ndim,ntot),intent(in) X, real(8),dimension(ndim),intent(in) theta, real(8),dimension(ntot,ntot),intent(out) Kmat)
Subroutine to create the covariance matrix between training points for a function-only Kriging model.
Definition at line 20 of file covarmatrix.f90.
References covars::covarfunc().
subroutine covarmatrix_mod::covarmatrix_training_grad (integer,intent(in) ndim, integer,intent(in) ntot, integer,intent(in) gtot, integer,dimension(gtot),intent(in) pts, integer,dimension(gtot),intent(in) dims, real(8),dimension(ndim,ntot),intent(in) X, real(8),dimension(ndim),intent(in) theta, real(8),dimension(ntot+gtot,ntot+gtot),intent(out) Kmat)
Subroutine to create covariance matrix between training points for gradient-enhanced Kriging model. This matrix is a block matrix where the diagonals represent covariance between function values and derivative values and the off-diagonals represent the covaraince between function and derivative values.
Definition at line 43 of file covarmatrix.f90.
References covars::covarfunc(), covars::d2covarfunc(), and covars::dcovarfunc().