ForK Library: patternsearch.f90 File Reference
patternsearch.f90 File Reference
Pattern Search used for global optimization
Used for max likelihood optimization and determining min/max values from Kriging surface.
Functions/Subroutines
subroutine patternsearch (odim, Xl, Xf, Fmin, L, U, flag, args)
The pattern search is a function-only optimization method suitable for global optimization problems. Given an initial function evaluation, the pattern search performs additional function evaluations in a set of fixed search directions about this initial point (with the same step size in each direction).
If one of the new function values is less than the initial function value, the center of the stencil is shifted to the new minimum value and the process is repeated about this new minimum point.
If none of the new function evaluations are less than the initial value, the center of the stencil is unchanged and additional function evaluations are performed using half the step size. The process is repeated until the step size is sufficiently small or the relative change in the function value is below a specified tolerance.
Detailed Description
Pattern Search used for global optimization
Used for max likelihood optimization and determining min/max values from Kriging surface.
Definition in file patternsearch.f90.
Function Documentation
subroutine patternsearch (integer,intent(in) odim, real(8),dimension(odim),intent(in) Xl, real(8),dimension(odim),intent(out) Xf, real(8),intent(out) Fmin, real(8),dimension(odim),intent(in) L, real(8),dimension(odim),intent(in) U, integer,intent(in) flag, type (generalarg) args)
The pattern search is a function-only optimization method suitable for global optimization problems. Given an initial function evaluation, the pattern search performs additional function evaluations in a set of fixed search directions about this initial point (with the same step size in each direction).
If one of the new function values is less than the initial function value, the center of the stencil is shifted to the new minimum value and the process is repeated about this new minimum point.
If none of the new function evaluations are less than the initial value, the center of the stencil is unchanged and additional function evaluations are performed using half the step size. The process is repeated until the step size is sufficiently small or the relative change in the function value is below a specified tolerance.
The directions used in this pattern search are the positive and negative coordinate directions of the design space. This choice leads to \(2N\) total search directions (and consequently \(2N\) function evaluations per iteration).
For more details, refer to Pattern_search_(optimization).
This subroutine has shared memory parallelization using openmp. Because each step in the optimization requires \(2N\) independent function evaluations, these evaluations can be performed simultaneously on different threads. Although this parallelization is efficient from a scaling point of view, each thread requires a large memory footprint. In the case of likelihood evaluations (this also applies for some of the Kriging subroutines), each thread must compute and store the covariance matrix, requiring a large amount of stack memory. Hence, the environmental variable "OMP_STACKSIZE" must be set to a suitably large value to avoid a segmentation fault. A good rule of thumb is to base the STACKSIZE on the size of the covariance matrix. This matrix is \(NxN\) for a function only Kriging model and \(N(D+1)xN(D+1)\) for a gradient-enhanced model (where \(N\) is the number of training points and \(D\) is the dimension of the problem). The elements of this matrix are double precision real numbers and thus require \(8\) bytes of storage for each element. Using these rules, a suitable STACKSIZE can be set. In some cases, the desired number of threads must be reduced to allow for the larger STACKSIZE for each thread to fit in main memory. Because the optimization is the most expensive part of the Kriging construction, determining the proper STACKSIZE and using the maximum number of threads is well worth the possible aggrevation.
Author:
Brian Lockwood
Department of Mechanical Engineering
University of Wyoming
Date:
May 15, 2012
Parameters:
in) odim : Dimension of the optimization
in) Xl : Starting point for the optimization
out) Xf : Final optimal location
out) Fmin : Final optimal value
in) L : Lower bound for each variable
in) U : Upper bound for each variable
in) flag : Determines whether minimum or maximum value is found
flag = 0 Subroutine finds the minimum value
flag = 1 Subroutine finds the maximum value
in) args : Structure containing additional arguments required for the function call
These structures are in the module argument
The structures for each function type are housed within the structure "generalarg" and the subroutine funcwrapper detects the function type and selects the proper element of "generalarg"
Definition at line 40 of file patternsearch.f90.
References opt::contractionfunc(), opt::expansionfunc(), opt::forcingfunc(), and funcwrapper().
Referenced by hyperparameters_all_mod::hyperparameters_all_func(), hyperparameters_all_mod::hyperparameters_all_grad(), hyperparameters_mle_mod::hyperparameters_mle_func(), hyperparameters_mle_mod::hyperparameters_mle_grad(), krigingextremefuncpredict(), krigingextremefuncpredictGEK(), krigingmaxeipredict(), krigingmaxeipredictGEK(), krigingmaxvariancepredict(), and krigingmaxvariancepredictGEK().