ForK Library: simplexsearch.f90 File Reference
simplexsearch.f90 File Reference
Simplex Search used for optimization
Used for max likelihood optimization and determining min/max values from Kriging surface
Suitable for fast local optimization using function values.
Functions/Subroutines
subroutine simplexsearch (odim, Xl, Xf, Fmin, L, U, flag, args)
This subroutine implements the Nelder-Mead method for optimization applied to the max likelihood problem and optimization performed on the Kriging surface itself.
For this method, a simplex element in \(N\) dimensions (set by the argument odim) is constructed and the search direction for new function values is constructed based on the vertices and faces of this element. The procedure for determining the minimum value is outlined below. For maximization, all function values can be multiplied by \(-1\) and the minimization algorithm can be applied.
Detailed Description
Simplex Search used for optimization
Used for max likelihood optimization and determining min/max values from Kriging surface
Suitable for fast local optimization using function values.
Definition in file simplexsearch.f90.
Function Documentation
subroutine simplexsearch (integer,intent(in) odim, real(8),dimension(odim),intent(in) Xl, real(8),dimension(odim),intent(out) Xf, real(8),intent(out) Fmin, real(8),dimension(odim),intent(in) L, real(8),dimension(odim),intent(in) U, integer,intent(in) flag, type (generalarg) args)
This subroutine implements the Nelder-Mead method for optimization applied to the max likelihood problem and optimization performed on the Kriging surface itself.
For this method, a simplex element in \(N\) dimensions (set by the argument odim) is constructed and the search direction for new function values is constructed based on the vertices and faces of this element. The procedure for determining the minimum value is outlined below. For maximization, all function values can be multiplied by \(-1\) and the minimization algorithm can be applied.
Starting with \(N + 1\) function evaluations, the maximum function value in the element is determined (\(F_{max}\))
The search direction is given by the vector between the maximum function value of the element and the centroid of the remaining vertices.
\[\vec{p} = \vec{X}_{face} - \vec{X}_{max}\]
where
\[\vec{X}_{face} =\frac{1}{N} \sum_{i \ne max} \vec{X}_{i}\]
A line search is next performed in this direction to determine the new candidate point. The following points are tested.
Reflected point: \(\vec{X}_{r} = \vec{X}_{face} + \vec{p} \)
Expanded point: \(\vec{X}_{e} = \vec{X}_{face} + 2 \vec{p} \)
Outside Contraction: \(\vec{X}_{oc} = \vec{X}_{face} + \frac{1}{2} \vec{p} \)
Inside Contraction: \(\vec{X}_{ic} = \vec{X}_{face} - \frac{1}{2} \vec{p} \)
If the reflected point's function value is the new minimum value, the expanded point is tested.
If the reflected point's function value is less than the previous maximum value in the element but would still correspond to the maximum vertex value in the element, outside contraction is performed.
If the reflected point's function value is greater than the previous maximum value, inside contraction is performed.
Based on the results of the line search, the previous maximum vertex value is replaced by the best candidate determined in the line search (either the reflected point, expanded point, outside contraction or inside contraction).
In the event that none of the candidate locations tested in the line search are able to reduce the maximum function value of the element, a rescaling is performed around the minimum location.
\[ \vec{X}'_{i} = \vec{X}_{min} + \frac{1}{2} (\vec{X}_{i} - \vec{X}_{min}) \]
More details of this algorithm can be found in Numerical Optimization by Nocedal and Wright
Author:
Brian Lockwood
Department of Mechanical Engineering
University of Wyoming
Date:
May 15, 2012
Parameters:
in) odim : Dimension of the optimization
in) Xl : Starting point for the optimization
out) Xf : Final optimal location
out) Fmin : Final optimal value
in) L : Lower bound for each variable
in) U : Upper bound for each variable
in) flag : Determines whether minimum or maximum value is found
flag = 0 Subroutine finds the minimum value
flag = 1 Subroutine finds the maximum value
in) args : Structure containing additional arguments required for the function call
These structures are in the module argument
The structures for each function type are housed within the structure "generalarg" and the subroutine funcwrapper detects the function type and selects the proper element of "generalarg"
Definition at line 52 of file simplexsearch.f90.
References funcwrapper().
Referenced by hyperparameters_all_mod::hyperparameters_all_func(), hyperparameters_all_mod::hyperparameters_all_grad(), hyperparameters_mle_mod::hyperparameters_mle_func(), hyperparameters_mle_mod::hyperparameters_mle_grad(), krigingextremefuncpredict(), krigingextremefuncpredictGEK(), krigingmaxeipredict(), krigingmaxeipredictGEK(), krigingmaxvariancepredict(), and krigingmaxvariancepredictGEK().